# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: backend
  - group: var

  

stages:
- stage: tfdestroy
  jobs:
  - job: destroy
    steps:

    - task: AzureKeyVault@2
      displayName: Fetch keyvault
      inputs:
        azureSubscription: 'miyoming_vm'
        KeyVaultName: 'miyoming-keyvault'
        SecretsFilter: '*'
        RunAsPreJob: false  

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: '1.15.9'

    - task: TerraformTask@5
      displayName: Terraform init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'miyoming_vm'
        backendAzureRmResourceGroupName: '$(strgrg)'
        backendAzureRmStorageAccountName: '$(stgacct)'
        backendAzureRmContainerName: '$(stgcont)'
        backendAzureRmKey: '$(stgkey)'


    - task: TerraformTask@5
      displayName: Terraform destroy
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        environmentServiceNameAzureRM: 'miyoming_vm'
      env:
          TF_VAR_nsg_name: $(nsg_name)
          TF_VAR_nsg_rules: $(nsg_rules)
